/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Button: typeof import('primevue/button')['default']
    Card: typeof import('primevue/card')['default']
    Chart: typeof import('primevue/chart')['default']
    Column: typeof import('primevue/column')['default']
    DataTable: typeof import('primevue/datatable')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    ProductsChart: typeof import('./src/components/ProductsChart.vue')['default']
    ProductsTable: typeof import('./src/components/ProductsTable.vue')['default']
    SalesByCategories: typeof import('./src/components/SalesByCategories.vue')['default']
    SalesCategories: typeof import('./src/components/SalesCategories.vue')['default']
    SalesProducts: typeof import('./src/components/SalesProducts.vue')['default']
    Skeleton: typeof import('primevue/skeleton')['default']
    TopProducts: typeof import('./src/components/TopProducts.vue')['default']
    TotalSales: typeof import('./src/components/TotalSales.vue')['default']
  }
}
